version: '1'
services:
  backend:
    build: ./Code/crowdinfra_backend 
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Code/crowdinfra_backend:/app  
      - /app/node_modules 
    command: ["npx", "nodemon", "server.js"]  
    depends_on:
      - frontend

  frontend:
    build: ./Code/crowdinfra_frontend 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Code/crowdinfra_frontend:/app  
      - /app/node_modules  
    command: ["npm", "run", "dev"]  
